defaults = {'model_name': 'OPT',
            'model_size': '1.3b',
            'prompt_connection': 'input/output',
            'k': 7,
            'top_k': 50,
            'top_p': 0.9,
            'do_sample': True,
            'num_beams': 1,
            'num_return_sequences': 1,
            'temperature': 1.0,
            'early_stopping': True,
            'tqdm': True,
            'task_def': "Definition: what is a polite and nice way of saying the sentence without any offensive words - ",
            }
